// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWHImSkfmK7WauIFa0h8mb1oBoaOoqOk',
    appId: '1:936632880190:web:edcaa5bc1649f195ff956f',
    messagingSenderId: '936632880190',
    projectId: 'mumbojumbo-1620b',
    authDomain: 'mumbojumbo-1620b.firebaseapp.com',
    storageBucket: 'mumbojumbo-1620b.appspot.com',
    measurementId: 'G-DM1Y5MKMMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvi8WMI33paHaO35GubO-apR1_8Txyc4',
    appId: '1:936632880190:android:308b945b3bdd3ad1ff956f',
    messagingSenderId: '936632880190',
    projectId: 'mumbojumbo-1620b',
    storageBucket: 'mumbojumbo-1620b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ZV9LopeZGjCXbUWge9Sz_QKSHRezC_Q',
    appId: '1:936632880190:ios:b7d0c4972fc1276eff956f',
    messagingSenderId: '936632880190',
    projectId: 'mumbojumbo-1620b',
    storageBucket: 'mumbojumbo-1620b.appspot.com',
    iosBundleId: 'com.example.mumbojumbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ZV9LopeZGjCXbUWge9Sz_QKSHRezC_Q',
    appId: '1:936632880190:ios:b7d0c4972fc1276eff956f',
    messagingSenderId: '936632880190',
    projectId: 'mumbojumbo-1620b',
    storageBucket: 'mumbojumbo-1620b.appspot.com',
    iosBundleId: 'com.example.mumbojumbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGWHImSkfmK7WauIFa0h8mb1oBoaOoqOk',
    appId: '1:936632880190:web:c987ee6060acd151ff956f',
    messagingSenderId: '936632880190',
    projectId: 'mumbojumbo-1620b',
    authDomain: 'mumbojumbo-1620b.firebaseapp.com',
    storageBucket: 'mumbojumbo-1620b.appspot.com',
    measurementId: 'G-NN316MWF5B',
  );
}
